// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS7aL-rSylHtQC5_70j37225XQVY__Ot4',
    appId: '1:8161462488:web:c655f44eb4421bd27b2fad',
    messagingSenderId: '8161462488',
    projectId: 'tubes-ubihard',
    authDomain: 'tubes-ubihard.firebaseapp.com',
    storageBucket: 'tubes-ubihard.appspot.com',
    measurementId: 'G-PMKG46NVT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnsyRxVD8MfWfpkFjnZqRjgfZkEEO_Pe0',
    appId: '1:8161462488:android:3c24aed5af6117047b2fad',
    messagingSenderId: '8161462488',
    projectId: 'tubes-ubihard',
    storageBucket: 'tubes-ubihard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7aPvw_lqZiGdPy5vR1TCemXofgbahUKY',
    appId: '1:8161462488:ios:4a82ea68d54bf04f7b2fad',
    messagingSenderId: '8161462488',
    projectId: 'tubes-ubihard',
    storageBucket: 'tubes-ubihard.appspot.com',
    iosBundleId: 'com.example.tugasLayout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7aPvw_lqZiGdPy5vR1TCemXofgbahUKY',
    appId: '1:8161462488:ios:03389689e9b97ee87b2fad',
    messagingSenderId: '8161462488',
    projectId: 'tubes-ubihard',
    storageBucket: 'tubes-ubihard.appspot.com',
    iosBundleId: 'com.example.tugasLayout.RunnerTests',
  );
}
