// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Ca9aEZlWrhWABeVw9figlFpyBOHt_QE',
    appId: '1:896555974474:web:71a47533161305e2140bb3',
    messagingSenderId: '896555974474',
    projectId: 'nitrogapp-tubes',
    authDomain: 'nitrogapp-tubes.firebaseapp.com',
    storageBucket: 'nitrogapp-tubes.appspot.com',
    measurementId: 'G-BYWH0YW4HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNMdzrclre9BnZ1cozrlppFV1dzbWhMjA',
    appId: '1:896555974474:android:d13752bc5fcb0a1f140bb3',
    messagingSenderId: '896555974474',
    projectId: 'nitrogapp-tubes',
    storageBucket: 'nitrogapp-tubes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARP4glyebEAGxXE2viVF-Hwmiu3dRn1mA',
    appId: '1:896555974474:ios:ffce9a7140dff3d4140bb3',
    messagingSenderId: '896555974474',
    projectId: 'nitrogapp-tubes',
    storageBucket: 'nitrogapp-tubes.appspot.com',
    androidClientId: '896555974474-0lctqnqt1mqhaiipsunl044jp46fddhd.apps.googleusercontent.com',
    iosClientId: '896555974474-ghj92ldtshd0ar9ikgdr6b70c2rluprp.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasLayout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARP4glyebEAGxXE2viVF-Hwmiu3dRn1mA',
    appId: '1:896555974474:ios:d116d92b0254f1e5140bb3',
    messagingSenderId: '896555974474',
    projectId: 'nitrogapp-tubes',
    storageBucket: 'nitrogapp-tubes.appspot.com',
    androidClientId: '896555974474-0lctqnqt1mqhaiipsunl044jp46fddhd.apps.googleusercontent.com',
    iosClientId: '896555974474-a2nocb2c2pmrdrhf6jj8869n62dj1a9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasLayout.RunnerTests',
  );
}
